server {
    listen 8080;  # ❌ CONFLIT avec server1
    server_name server2.local;
    host 127.0.0.1;
    root ./www_server2;
    index index.html;
    
    location / {
        allowed_methods GET POST;
        autoindex on;
    }
}

server {
    listen 8080;
    server_name server2.local;
    host 127.0.0.1;
    root ./www_server2_alt;
    index index.html;
    
    location / {
        allowed_methods GET;
        autoindex on;
    }
}