# Configuration pour tests CGI
server {
    listen 8080;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 1000000;
    
    error_page 404 /404.html;
    
    location / {
        allowed_methods GET POST DELETE;
        autoindex off;
    }
    
    location /cgi-bin {
        allowed_methods GET POST;
        cgi_extension .sh .py;
        cgi_path /bin/bash;
    }
    
    location /upload {
        allowed_methods PUT POST;
        upload_path ./uploads;
    }
}
