server {
    listen 8080;
    
    server_name localhost;
    host 127.0.0.1;
    root ./www;
    index index.html index.htm;
    
    client_max_body_size 10000000;
    
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    
    location / {
        allowed_methods GET POST;
        autoindex off;
    }
    
    location /upload {
        allowed_methods POST;
        upload_path ./uploads;
    }
    
    location /cgi-bin {
        allowed_methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
    
    location /redirect {
        allowed_methods GET POST;
        return 301 https://www.google.com;
    }
}

server {
    listen 8081;
    server_name example.com;
    root ./www_example;
    index index.html;
    
    location / {
        allowed_methods GET POST DELETE;
        autoindex on;
    }
}

server {
    listen 8082;
    server_name example.com;
    root ./www_example;
    index index.html;
    
    location / {
        allowed_methods GET POST DELETE;
        autoindex on;
    }
}