server {
    listen 8080;
    server_name site1.local;
    host 127.0.0.1;
    root ./www;
    index index.html;
    
    location / {
        allowed_methods GET POST;
        autoindex off;
    }
}

server {
    listen 8081;
    server_name site2.local;
    host 127.0.0.1;
    root ./www_example;
    index index.html;
    
    location / {
        allowed_methods GET POST;
        autoindex on;
    }
}

server {
    listen 8082;
    server_name site3.local;
    host 127.0.0.1;
    root ./www;
    index index.html;
    
    location / {
        allowed_methods GET POST DELETE;
        autoindex off;
    }
}
